#%RAML 0.8
---
title: A sample RAML Rest Service for VOAG
version: 1.0
baseUri: https://localhost:8083/api

/order:
  post:
    description: Creat a new order in MySql Database
    body:
      application/json:
            schema: !include schemas/order.json
            example: !include example/order-example.json
       
    responses:
      201:
        description: |
          The order has been succesfully created
        headers:
          Location:
            type: string
            description: Location of the newly created order
      409:
        description: |
          The order already exists, note it  needs to be coded
  /{orderId}:
   get:
      description: The GET operation returns a specific Order by id
      responses:
        200:
          body:
            application/json:
              schema: !include schemas/order.json
              example: !include example/order-example.json                 
/inventory:
     get:
        description: Retrieve a list of Ordes from MySQl Database
        responses:
          200:
            body:
              application/json:
                schema:  !include schemas/inventory.json
                example: !include example/inventory-example.json
          404:
            description: |
               The order does not exist                   
   

 
